services:
  - type: web
    name: movie-mind
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: TMDB_BEARER_TOKEN
        sync: false

